### ISSUE TITLE
Current Ubuntu GCC 4.9 seems to be buggy

### ISSUE THREAD

**Issue by poulson** [JuliaParallel/Elemental.jl#1]
The current Travis output shows that there is an internal error in g++-4.9 when compiling Elemental: https://travis-ci.org/JuliaParallel/Elemental.jl/builds/59600456

Perhaps the Travis build should use g++-4.8 (or at least not put up a "build failing" logo for g++-4.9 errors)?

**Comment by poulson** [comment]
Perhaps the PPA being manually added by Travis has out-of-date versions of the compilers?

**Comment by andreasnoack** [comment]
The Travis error is because of too much memory usage.
