### ISSUE TITLE
Single node out of core/on disk matrices?

### ISSUE THREAD

**Issue by datnamer** [JuliaParallel/Elemental.jl#26]
Can this library be used for linear algebra on single node, out-of-core datastructures like Dato's Sarray or a database  if we can represent a database as an abstract matrix? Maybe if there is some way to chunk up the datastructure and stream it into memory?

**Comment by andreasnoack** [comment]
You can use it on a single node, but integrating it with out of core computations is not really on the agenda right now. If you have more specific ideas, feel free to prepare a proof and concept in a new issue.

**Comment by datnamer** [comment]
Understood thanks.
