### ISSUE TITLE
Building Elemental on mac

### ISSUE THREAD

**Issue by ViralBShah** [JuliaParallel/Elemental.jl#30]
Is building on a mac supported? The Elemental build failed with:

````
In file included from /Users/viral/.julia/v0.5/Elemental/deps/src/Elemental/src/blas_like/level1-C.cpp:9:
In file included from /Users/viral/.julia/v0.5/Elemental/deps/src/Elemental/include/El.hpp:15:
In file included from /Users/viral/.julia/v0.5/Elemental/deps/src/Elemental/include/El/core.hpp:182:
/Users/viral/.julia/v0.5/Elemental/deps/src/Elemental/include/El/core/Element/impl.hpp:562:43: error: 
      no matching function for call to 'round'
inline T Round( const T& alpha ) { return round(alpha); }
                                          ^~~~~
````

**Comment by poulson** [comment]
Hi Viral,

Yes, I had just temporarily broken master for Clang due to Ubuntu's GCC being more permissive. It should work now.

**Comment by poulson** [comment]
Amateur hour should finally be over:
https://github.com/elemental/Elemental/commit/94a329242c1c4c9cdaf42192f223a2ad91d5cc3a

**Comment by poulson** [comment]
I'll be flying blind with Clang support until Monday, but the following changeset attempts to make my new usages of `std::enable_if` closer to the C++14 implementation of `std::enable_if_t`: https://github.com/elemental/Elemental/commit/f34d44203fed11b6ca4f159f1ac64bc59edb3dcc

**Comment by ViralBShah** [comment]
Thanks @poulson. Trying again now.

**Comment by ViralBShah** [comment]
Now I get:

````
/Users/viral/.julia/v0.5/Elemental/deps/src/Elemental/include/El/core/Element/impl.hpp:602:30: error: 
      template parameter redefines default argument
template<typename T,typename=EnableIf<IsScalar<T>>>
 ````

**Comment by poulson** [comment]
@ViralBShah Progress! This should hopefully finish the job: https://github.com/elemental/Elemental/commit/57d89c9da11411ce3ec8e45f052b4f6255260a05

**Comment by ViralBShah** [comment]
I did a `git pull` in the Julia package directory where Elemental sources are checked out and doing `Pkg.build()` again. Is there a better way to do this?

**Comment by poulson** [comment]
I believe that is the best practice. Things have been much less stable than normal over the last week due to me pushing the library towards supporting some number theory (and my portable build cluster being half out of commission until Monday).

**Comment by ViralBShah** [comment]
Still seeing these. I wonder if I am doing something wrong with the build.

````
/Users/viral/.julia/v0.5/Elemental/deps/src/Elemental/include/El/core/Element/impl.hpp:561:30: error: 
      template parameter redefines default argument
template<typename T,typename=EnableIf<IsScalar<T>>>
````

**Comment by ViralBShah** [comment]
Wiped Elemental and restarting Pkg.build.

**Comment by ViralBShah** [comment]
Still dies with the same error as above.

**Comment by poulson** [comment]
No, you're not doing anything wrong, I'm just hamstrung due to my Clang machine being temporarily out-of-commission and GCC apparently being extremely permissive with SFINAE in comparison. I'm trying to fix this ASAP by setting up a clang environment.

**Comment by ViralBShah** [comment]
No worries. I can try again in a few days, once you get things running again.

**Comment by poulson** [comment]
I now have a replacement clang build environment put together (after issues with clang-3.5 and clang-3.6 segfaulting compiling MPICH on Ubuntu); fix immenent

**Comment by poulson** [comment]
@ViralBShah The clang build is now fixed for me as of this commit: https://github.com/elemental/Elemental/commit/45ac75a75ad6eb82de4ea840fd398d1ee8bd89be

Thanks for your patience!

**Comment by ViralBShah** [comment]
Build succeeded. Thanks.
