### ISSUE TITLE
Provide BB binaries

### ISSUE THREAD

**Issue by ViralBShah** [JuliaParallel/Elemental.jl#52]
Now that we are close to having MPI.jl use BB MPI binaries, it would be nice to have Elemental through BB too.

**Comment by andreasnoack** [comment]
How would that work with custom MPIs?

**Comment by ViralBShah** [comment]
I guess it would not. You have to be on your own then. Quite likely people with custom MPI are also using custom compilers.

**Comment by andreasnoack** [comment]
I think that, right now, we'd be able to compile against the custom MPIs. I'm curious how MPI.jl handles this case.

**Comment by ViralBShah** [comment]
MPI.jl is easier. Use an environment variable or some other mechanism to pick BB or system.

https://github.com/JuliaParallel/MPI.jl/issues/328

We can retain the scripts to compile against a system MPI.

**Comment by ViralBShah** [comment]
You could also retain the code to build and link against a system MPI, while having BB provided Elemental as default.

I think a meaningfully useful MPI setup with common MPI libs that works out of the box would greatly reduce dev effort and get us a working system out of the box.

Do we know if people compile Elemental against system MPI through the supplied build scripts in this package?

**Comment by ViralBShah** [comment]
@christopher-dG has built BB binaries for Elemental and we already have MPICH. The next step is to update this package to use them.

**Comment by christopher-dG** [comment]
Is 1.0 compatibility a priority? It can be done but it's simpler to just drop it.

**Comment by ViralBShah** [comment]
Drop it.

**Comment by ViralBShah** [comment]
I just realized that Elemental is forked by LLNL, and as per Elemental's github page, the LLNL fork is the currently maintained one. It also has a more recent release:

https://github.com/LLNL/Elemental

I updated the README to point to it.

**Comment by christopher-dG** [comment]
Yeah I saw it too, but went with the one that was already in use to avoid any breakage. In the future we should definitely look at the newer release.

**Comment by ViralBShah** [comment]
Yeah, I think that was the right decision. Use the one for now we know that works, but then get the new one in BB as well to pave the way for updating to the new one.

**Comment by christopher-dG** [comment]
Getting segfaults... https://travis-ci.org/github/JuliaParallel/Elemental.jl/jobs/674554725

**Comment by ViralBShah** [comment]
Is it a matter of just one test failing, or just about everything. I guess we have to get into some internals. @andreasnoack Are you familiar with this codebase?

**Comment by christopher-dG** [comment]
Here's the most recent one: https://travis-ci.org/github/JuliaParallel/Elemental.jl/jobs/674568005

Some stuff is passing, but about half of the cases are causing segfaults. It's kind of hard to tell though because the tests don't exist in a normal `@testset` (probably due to them needing to run via `mpiexec`).

**Comment by ViralBShah** [comment]
Do they fail on your local machine also?

**Comment by christopher-dG** [comment]
Yeah they do.

**Comment by ViralBShah** [comment]
I am unable to `dev Elemental` perhaps because it doesn't have a Project.toml.

**Comment by christopher-dG** [comment]
Yeah you'll have to clone manually and then checkout my branch. I'm also working on a `cdg/jll2` branch that contains more minimal changes to try to make sure that I'm not accidentally breaking anything.

**Comment by ViralBShah** [comment]
I wonder if we can add a `Project.toml` so it's easier to dev. I'll check it out manually in the meanwhile.

**Comment by andreasnoack** [comment]
I'll try to add a project file shortly and then we can use that version to compare with.

**Comment by andreasnoack** [comment]
I finally managed to get CI passing and have merged https://github.com/JuliaParallel/Elemental.jl/pull/55 so now we have a project file. I had to temporarily disable testing on Mac but will try to enable that again once Iøve figured out which compilers I'm now supposed to used on Travis macOS.

**Comment by christopher-dG** [comment]
And this week I'll be taking a deep dive trying to get the BB-compiled libEl to work...

**Comment by ViralBShah** [comment]
FWIW, the first sequential code example in the README is broken - so I don't think it is a BB binaries issue. Try the second or the third one, which works.

**Comment by christopher-dG** [comment]
I've just been basing it on the tests. About half of them segfault or something along those lines.

**Comment by ViralBShah** [comment]
Yeah - then there is no option but to dive in and fix the issues.

**Comment by andreasnoack** [comment]
The broken example was just because the convert method used the old array constructor without the `undef` part, see #60, so if there are segfaults it's definitely something deeper.

**Comment by ViralBShah** [comment]
Should we tag a new release now that we have the BB binaries. Perhaps open new issues on segfaults and such as we encounter?

**Comment by andreasnoack** [comment]
#54 would need to get merged first, rigth?
