### ISSUE TITLE
"ERROR: cannot serialize a pointer" with @async and @sync

### ISSUE THREAD

**Issue by andreasnoack** [JuliaParallel/Elemental.jl#8]
With the latest changes I've just pushed to master I can copy a `DArray` into `DistMatrix` on the MPI workers and get the `RemoteRef`s back. E.g.
```jl
julia> using MPI

julia> man = MPIManager(np = 2);

julia> addprocs(man);

julia> using DistributedArrays

julia> using Elemental

julia> A = drandn(100,100);

julia> tmp = Elemental.toback(A)
1x2 Array{Any,2}:
 RemoteRef{Channel{Any}}(2,1,16)  RemoteRef{Channel{Any}}(3,1,17)
```
and then I can compute the singular values with
```jl
julia> for r in tmp
       remotecall(() -> println(svdvals(fetch(r))), r.where)
       end

julia> 	From worker 3:	[19.928126878869584
	From worker 2:	[19.928126878869584
	From worker 3:	 19.248234662565334
	From worker 2:	 19.248234662565334
	From worker 2:	 18.378572289263257
	From worker 3:	 18.378572289263257
	From worker 2:	 18.271178929809935
```
which is fine and I will start wrapping this array of `RemoteRef`s in some type representing the remote `DistMatrix`. However, I'd like to use the `@sync for ... @async remotecall_wait` as well, but if I try
```jl
julia> @time @sync for r in tmp
       @async remotecall_fetch(() -> svdvals(fetch(r)), r.where)
       end
	From worker 3:	fatal error on 3: ERROR: cannot serialize a pointer
	From worker 2:	fatal error on 2: ERROR: cannot serialize a pointer
	From worker 3:	 in serialize at serialize.jl:418 (repeats 2 times)
	From worker 2:	 in serialize at serialize.jl:418 (repeats 2 times)
```
cc: @jakebolewski

**Comment by andreasnoack** [comment]
See https://github.com/JuliaLang/julia/pull/13190

**Comment by JeffBezanson** [comment]
Does this use case require serializing pointers bit-for-bit, or would it be enough to deserialize them as NULL?

**Comment by andreasnoack** [comment]
I'm pretty sure that NULL is fine. I shoud be able to avoid serializing pointers, but the main problem is when developing, I sometimes accidentially fetch a pointer and all my workers crash.

**Comment by andreasnoack** [comment]
Fixed by https://github.com/JuliaLang/julia/commit/77b2527fd91878d69d69908b60c29d977d2f8e92 and https://github.com/JuliaLang/julia/commit/aa1076d36e984b5ab0d5a808f4909707a5de24ab. Now we only have to wait on 0.5.
